apiVersion: blueprints.cloud.google.com/v1alpha1
kind: TerraformBlueprint
metadata:
  name: terraform-google-cloud-sql
  source:
    type: git
    git:
      repo: https://github.com/GoogleCloudPlatform/terraform-google-cloud-sql.git
      dir: /
  version: 1.0.0
  actuationTool:
    type: Terraform
    versions:
      - ">= 1.3"
  title: Google Cloud SQL Module
  icon: https://cloud.google.com/images/products/icons/sql.svg
  description:
    tagline: Provisions a Google Cloud SQL instance with databases and users.
    detailed: This module provisions a Google Cloud SQL instance, databases, and users, adhering to enterprise best practices for security, reliability, and maintainability. It supports PostgreSQL, MySQL, and SQL Server database engines.
  documentation:
    - title: Cloud SQL Provider Docs
      url: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance
  labels:
    - gcp
    - sql
    - database
    - rdbms
spec:
  requirements:
    services:
      - sqladmin.googleapis.com
      - compute.googleapis.com
      - cloudkms.googleapis.com
    roles:
      - role: roles/sqladmin.admin
        level: project
      - role: roles/compute.networkUser
        level: project
        description: Required if using a shared VPC network for the private IP.
      - role: roles/cloudkms.cryptoKeyEncrypterDecrypter
        level: project
        description: Required on the KMS key if using a customer-managed encryption key (CMEK).
  customization:
    variables:
      - name: project_id
        description: The ID of the project in which the resource belongs.
        varType: string
        required: true
      - name: name
        description: The name of the Cloud SQL instance. This does not include the project ID.
        varType: string
        required: true
      - name: database_version
        description: The database engine version to use. See https://cloud.google.com/sql/docs/db-versions for supported versions. E.g., `MYSQL_8_0`, `POSTGRES_14`.
        varType: string
        required: true
      - name: region
        description: The region where the instance will be located.
        varType: string
        required: true
      - name: tier
        description: The machine type to use. See https://cloud.google.com/sql/docs/instance-settings for details.
        varType: string
        required: true
      - name: deletion_protection
        description: Used to block Terraform from deleting a SQL Instance. Recommended to be `true` for production instances.
        varType: bool
        default: true
      - name: availability_type
        description: The availability type of the Cloud SQL instance. Can be `ZONAL` or `REGIONAL`. `REGIONAL` instances provide high availability and are recommended for production.
        varType: string
        default: "REGIONAL"
      - name: disk_autoresize
        description: This setting enables the automatic increase of storage size when the instance is running out of disk space. Recommended to be `true`.
        varType: bool
        default: true
      - name: disk_autoresize_limit
        description: The maximum size in GB to which storage can be auto-increased. A value of 0 means no limit. It is recommended to set a limit for cost control.
        varType: number
        default: 0
      - name: disk_size
        description: The size of the storage in gigabytes.
        varType: number
        default: 10
      - name: disk_type
        description: The type of storage to use. Can be `PD_SSD` or `PD_HDD`.
        varType: string
        default: "PD_SSD"
      - name: edition
        description: The edition of the instance, can be `ENTERPRISE` or `ENTERPRISE_PLUS`. `ENTERPRISE_PLUS` provides the highest availability.
        varType: string
        default: "ENTERPRISE"
      - name: root_password
        description: The password for the root user. If not set, a random one will be generated. Required for SQL Server instances. It is recommended to use Secret Manager to manage this value.
        varType: string
        default: null
        sensitive: true
      - name: encryption_key_name
        description: The full name of the Cloud KMS key to be used for encrypting the disk. The key must be in the same region as the instance.
        varType: string
        default: null
      - name: require_ssl
        description: Whether SSL connections are required for this instance. This is a security best practice.
        varType: bool
        default: true
      - name: ip_configuration
        description: The IP configuration for the instance. See https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#ip_configuration.
        varType: object
        default:
          ipv4_enabled: false
      - name: backup_configuration
        description: The backup configuration for the instance. Backups are enabled by default.
        varType: object
        default: {}
      - name: maintenance_window
        description: The maintenance window for the instance. See https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#maintenance_window.
        varType: object
        default: null
      - name: database_flags
        description: List of database flags to apply to the instance. IAM database authentication is enabled by default.
        varType: list(object)
        default:
          - name: cloudsql.iam_authentication
            value: "On"
      - name: databases
        description: A list of databases to be created in the instance.
        varType: list(object)
        default: []
      - name: users
        description: A list of users to be created in the instance. It is recommended to use Secret Manager to manage passwords.
        varType: list(object)
        default: []
        sensitive: true
    variableGroups:
      - name: Basic Instance Configuration
        description: Core settings for the Cloud SQL instance.
        variables:
          - project_id
          - name
          - region
          - database_version
          - tier
          - edition
          - availability_type
      - name: Storage and Protection
        description: Configuration for instance storage and deletion protection.
        variables:
          - disk_size
          - disk_type
          - disk_autoresize
          - disk_autoresize_limit
          - deletion_protection
      - name: Networking and Security
        description: Settings for network access, encryption, and authentication.
        variables:
          - ip_configuration
          - require_ssl
          - root_password
          - encryption_key_name
      - name: Backup and Maintenance
        description: Configuration for automated backups and maintenance windows.
        variables:
          - backup_configuration
          - maintenance_window
      - name: Advanced Configuration
        description: Databases, users, and custom database flags.
        variables:
          - database_flags
          - databases
          - users
    outputs:
      - name: instance_name
        description: The name of the Cloud SQL instance.
      - name: instance_connection_name
        description: The connection name of the instance to be used by the Cloud SQL Proxy.
      - name: private_ip_address
        description: The private IP address assigned to the instance.
      - name: public_ip_address
        description: The public IP address assigned to the instance.
      - name: self_link
        description: The URI of the created resource.
      - name: created_databases
        description: A map of the databases created in the instance.
      - name: created_users
        description: A map of the users created in the instance.
        sensitive: true
